[18.0][MIG] product_state: Migration to 18.0
natuan9/product-attribute pull request #1
Opened 2024-11-29 01:46 UTC by natuan9

2024-11-29 02:34 UTC, LucasTran380381 commented
Could you fix test

I see failed due to warning log?

2024-11-29 09:22 UTC, LucasTran380381 commented
I suggest fix this warning ( just use odoo-checklog for non-test-case module)

2024-12-02 02:15 UTC, natuan9 commented
Hi @LucasTran380381 , test issue has been fixed, pls help to review it

2024-12-02 10:00 UTC, LucasTran380381 requested changes

2024-12-02 10:00 UTC, LucasTran380381 commented on product_state/views/product_template_views.xml
> +                <field name="state" readonly="True" />
why you add `readonly` field `state` is computed field => it readonly by default ?

2024-12-02 10:00 UTC, LucasTran380381 commented on product_state/views/product_template_views.xml
> +                <field name="state" invisible="1" readonly="True" />
It see field `state` is invisible why  could not removed it ?

2024-12-03 03:05 UTC, LucasTran380381 approved these changes

2024-12-26 03:25 UTC, closed without merging

2025-01-02 08:45 UTC, thienvh332 commented
Hi @natuan9 , Your new `ir.model.access.csv` is blocking internal users from accessing the product. Please update this issue.
![image](https://github.com/user-attachments/assets/6d9d7772-96b0-4e9c-a16e-d4d89c9d6a44)